config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'posts#index'

  get '/imprint'  => 'home#imprint',  as: :imprint
  get '/about_us' => 'home#about_us', as: :about_us
  get '/team'     => 'home#team',     as: :team
  get '/faq'      => 'home#faq',      as: :faq

  get  '/offers/new' => 'offers#new',  as: :new_offer
  get  '/offers/:id' => 'offers#show', as: :offer
  post '/offers/:id' => 'offer_inquiries#create'

  resources :offers do
    resources :offer_inquiries, only: ['new', 'create', 'show', 'index']
  end

  resources :posts
end

app/models/offer.rb
class Offer < ActiveRecord::Base

  extend FriendlyId
  friendly_id :title, use: :slugged

  has_many :offer_inquiries

end

app/models/offer_inquiry.rb
class OfferInquiry < ActiveRecord::Base
  belongs_to :offer

  validates :name,    presence: { message: 'name' }
  validates :email,   presence: { message: 'email' }
  validates :message, presence: { message: 'message' }
end

app/models/post.rb
class Post < ActiveRecord::Base

  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :author, class_name: 'User', foreign_key: 'author_user_id'

  # mount_uploader :main_image, MainImageUploader

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def imprint
  end

  def about_us
  end

  def team
  end

  def faq
  end

end

app/controllers/offer_inquiries_controller.rb
class OfferInquiriesController < ApplicationController
  before_action :authenticate_user!, except: [:new, :create]

  def index
    @inquiries = OfferInquiry.all
  end

  def show
    @inquiry = OfferInquiry.find(params[:id])
  end

  def new
    @offer = Offer.friendly.find(params[:id])
    @inquiry = OfferInquiry.new
  end

  def create
    @offer = Offer.friendly.find(params[:id])
    @inquiry = OfferInquiry.new(inquiry_params)
    @inquiry.offer_id = @offer.id

    if @inquiry.save
      flash[:notice] = "Your message has been sent! We will contact you shortly"
      redirect_to offer_path(params[:id])
    else
      flash[:notice] = "Following fields are required: #{@inquiry.errors.messages.values.join(', ')}. Please fill it in."
      redirect_to :back
    end

    # respond_to do |format|
    #   if @inquiry.save
    #     # redirect_to offer_path(params[:id])
    #     # flash[:notice] = "Your message has been sent! We will contact you shortly"
    #     format.html { redirect_to :offer_path,
    #       flash[:notice] = "Your message has been sent! We will contact you shortly" }
    #     # format.json { render :show, status: :created, location: @offer }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @offer.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  private
    def inquiry_params
      params.require(:inquiry).permit!
    end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.order(created_at: :desc)
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
    @offer = Offer.friendly.find(params[:id])
    @inquiry = OfferInquiry.new(offer: @offer)
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params)

    respond_to do |format|
      if @offer.save
        format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: 'Offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit!
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order(created_at: :desc)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.friendly.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.author = current_user

    if params[:main_image].present?
      preloaded = Cloudinary::PreloadedFile.new(params[:main_image])
      raise "Invalid upload signature" if !preloaded.valid?
      @post.main_image = preloaded.identifier
    end

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit!
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown(text)
    return if text.blank?
    Kramdown::Document.new(text).to_html.html_safe
  end

end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/about_us.html.haml
%h1 About

%p Elskamor is a Berlin-based travel platform for vegans and vegetarians and anyone else looking to expand their boundaries and rise to the occasion. Since the summer of 2014 Elskamor has been offering the best retreats featuring the most nourishing foods in some of the worlds most inspiring places.
%p One part love for yourself, one part love for the world, Elskamor combines physical and mental challenges with great food and local culture. Our offers are hand picked, off-the-beaten path destinations amidst breathtaking natural beauty.
%p Elskamor is not your traditional travel platform, but rather a resource for vegetarian and vegans looking to get the most out of their experience traveling the world.

%h1 Why the Name Elskamor

%p Elskamor stands for double love: Elska means “love” in Icelandic and of course “amor” everyone knows. The two put together make Elsk(a)more.
%p Elskamor means love for your body and mind as well as love for the planet. It combines love for travel and adventure with love for nourishing vegan and vegetarian food.

%h1 Our Values

%p We want to have a conversation about eating a plant based diet, about challenging yourself and expanding your comfort zone and about striving to be a kind and thoughtful human being.
%p Eskamor is an open place where everyone is welcome. We are not about being pure or strict or 100% anything. Instead Elskamor is about being informed and inspired. We want you to have fun while living according to values such as kindness and respect.
%p We strive towards a wholly plant-based diet, towards regular exercise and meditation and towards interacting with the world and its inhabitants in a kind and respectful way. But we also understand that this is a process. To borrow a catchphrase: It’s all about progress not perfection, people!

app/views/home/faq.html.haml
%h1 Our mission

%p Elskamor wants to makes it easier for vegetarians and vegans to explore this beautiful world. We believe that exploration of our surroundings as well as our inner and outer selves is vital to our well-being. As such, we want to encourage travelers to experience this world differently.
%p Elskamor is the place for vegans and vegetarians to book travels that combine activities such as yoga and surfing with amazing plant based food. Being aspiring vegans ourselves we know that the most beautiful and secluded beaches often do not have the best vegan food. We are here to help you find the ones that do.
%p We want to you to be able to go wherever you want to go and do what whatever you want to do. Surfing in Portugal? Climbing in Sardinia? Hiking in Germany? If you travel through us you can do all that and never have to worry about where you will find the food that agrees with your stomach and values at the end of the day.

%h1 How it works

%p Our two main passions are adventure travel and amazing food. Elskamor will create strong partnerships with travel providers that share our passion and compassion thereby providing a superior experience for the curious and caring voyager.
%h3 This is how you can find and book your next voyage.
%ol
  %li Find the retreat of your dreams by browsing our offers or searching for a specific activity (yoga, climbing, surfing, …), country or type of cuisine (vegan, vegetarian, glutenfree, flexitarian).
  %li Be inspired and fall in love with one of our offers.
  %li Book directly on our website.

%p That’s it - we like to keep things simple! You still have to do the packing though.

%h1 Get Involved

%p We want YOU to be part of our community. If you feel inspired to get involved we want to hear from you. Drop us a line if you have a trip idea, want to recommend a teacher or adventure guide, tell us about an amazing retreat destination, or anything else that you want to share with us.
%p Email us: contact@elskamor.com.

%h1 Partners

%p We are continually looking for opportunities to form new partnerships. If you identify with our mission and share our objectives we would love to hear from you! Email us at contact@elskamor.com

app/views/home/imprint.html.haml
%h1 Impressum
%h2 Angaben gemäß § 5 TMG:
%p
  Berdugo, Jaszewska, Schachtschneider GbR
  %br/
  Wolliner Str. 64
  %br/
  10435 Berlin
%h2 Vertreten durch:
%p
  Maria Berdugo
  %br/
  Anita Jaszewska
  %br/
  Anna Schachtschneider
%h2 Kontakt:
%table
  %tr
    %td Telefon:
    %td +4915222414522
  %tr
    %td E-Mail:
    %td contact@elskamor.com
%h2 Umsatzsteuer-ID:
%p
  Umsatzsteuer-Identifikationsnummer gemäß §27 a Umsatzsteuergesetz:
  %br/
  1234567890
%h2 Verantwortlich für den Inhalt nach § 55 Abs. 2 RStV:
%p
  Anna Schachtschneider
  %br/
  Maria Berdugo
%h2 Quellenangaben für die verwendeten Bilder und Grafiken:
%p Alle Bilder unterliegen der Creative-Commons-Lizenz. Ausgenommen sind anders gekennzeichnete Bilder unter anderem von Pixabay sowie Pressefotos oder verlagseigenes Bildmaterial.

%hr

%h1 Haftungsausschluss (Disclaimer)
%p
  %strong Haftung für Inhalte
%p Als Diensteanbieter sind wir gemäß § 7 Abs.1 TMG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 TMG sind wir als Diensteanbieter jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden von entsprechenden Rechtsverletzungen werden wir diese Inhalte umgehend entfernen.
%p
  %strong Haftung für Links
%p Unser Angebot enthält Links zu externen Webseiten Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße überprüft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Links umgehend entfernen.
%p
  %strong Urheberrecht
%p Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser Seite sind nur für den privaten, nicht kommerziellen Gebrauch gestattet. Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter beachtet. Insbesondere werden Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte umgehend entfernen.
%p
%p
  %em
    Quellen:
    %br
    %a{:href => "http://www.e-recht24.de", :rel => "nofollow"} e-recht24.de
    speziell für Gesellschaft bürgerlichen Rechts (GbR) erzeugt.
    %br
    %a{:href => "http://www.e-recht24.de/muster-disclaimer.html", :rel => "nofollow", :target => "_blank"} e-recht24.de/muster-disclaimer

app/views/home/team.html.haml
%h1 Team
%p We are an international team of three women based in Berlin, Germany. Our backgrounds range from online marketing to financial services to grassroots political campaigns but we are united in our passion for appreciating the wonders of the world.

%h1 Maria Berdugo – Co-Founder/PR and Marketing
%p Maria is a world citizen at heart, she has lived one-third of her life in three different continents, Latin America, North America and Europe so travelling is part of her genetics. She is hooked on an active lifestyle and loves to discover and connect with nature, exchange ideas with people, and fuel herself with amazing food! She is actively pursuing a plant-based nutrition and enjoys sharing her “food journey” as it keeps having a phenomenally positive and transformative effect on her life. maria@elskamor.com

%h1 Anita Jaszewska – Co-Founder/Product and Developer
%p Anita is a strong karma believer, who enjoys being close to nature and meeting people from different cultures. She is crazy about technology, and loves tinkering with electronics. In addition, she can’t stay for too long in one place, so travelling is by default a major passion of hers.

anita@elskamor.com

%h1 Anna Schachtschneider – Co-Founder/Business Development and Editorial
%p Anna is a passionate environmentalist looking to change the world in a good and meaningful way. She has experience in grassroots campaigns, political organizing and the start-up world. She is also an amazing cook and keeps the team happy with vegan treats.
anna@elskamor.com

app/views/layouts/_body.html.haml
%body
  / Google Tag Manager
  %noscript
    %iframe{:height => "0", :src => "//www.googletagmanager.com/ns.html?id=GTM-MFP3WT", :style => "display:none;visibility:hidden", :width => "0"}
  :javascript
    (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-MFP3WT');
  / Facebook social plugin
  #fb-root
  :javascript
    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&appId=503914106375536&version=v2.0";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
  //
  #navbar-top.collapse.navbar-collapse
    .container
      %a.navbar-brand{href: root_path}
        ELSKAMOR
      %ul.nav.navbar-nav.navbar-right
        %li
          %a{href: root_path} Home
        %li
          %a{href: posts_path} Blog
        %li
          %a{href: offers_path} Offers
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown"}
            About
            %b.caret
          %ul.dropdown-menu
            %li.disabled
              %a= link_to 'Team', team_path
            %li.disabled
              %a= link_to 'About us', about_us_path
            %li.disabled
              %a= link_to 'How does it work?', faq_path
            %li.disabled
              %a= link_to 'Imprint', imprint_path
        - if user_signed_in?
          %li
            %a= link_to 'Inquiries', offer_offer_inquiries_path(1)
          %li
            = link_to 'Sign out', destroy_user_session_path
        -else
          %li
            %a{href: new_user_session_path} Sign in

  %section#header{style: "background-image: url('http://33.media.tumblr.com/ba7758a52675589e05dc931572be9688/tumblr_n7ygur3NV91st5lhmo1_1280.jpg');"}
    .container.text-center
      .landing-logo
        = image_tag("elskamor_transparent_white.png", height:'100px')
        %h2{style: "color: white; font-family: 'Raleway', sans-serif;"}
          Travel inspiration and adventures
          %br
          for the caring voyager

  .flash-messages
    - flash.each do |name, msg|
      - if msg.is_a?(String)
        .alert.alert-info.alert-dismissable
          %a.close{"data-dismiss" => "alert"} &times;
          %p.text-center= content_tag :span, msg, :id => "flash_#{name}"

app/views/layouts/_footer.html.haml
%section#footer
  .container
    .row
      .col-md-4
        .widget
          %h3 Learn about inspiring people, beautiful places and nourishing food. We present a selection of the amazing projects happening around the world that are in harmony with our values and ensure an all-around healthy lifestyle. Explore the blog and find some inspiration!
          .btn.btn-default= link_to 'Read the Blog', posts_path
      .col-md-4
        .widget
          %h3 Elskamor combines our love for travel and adventure with good and nourishing vegetarian and vegan food. We want you to be able to challenge yourself with physical and mental activities. Whatever your passion, be it yoga, surfing, rock climbing, or meditation, we strive to have something to offer for everyone.
          .btn.btn-default= link_to 'Look for Offers', offers_path
      .col-md-4
        .footer-logo
          %h2
            Elskamor
            / %i.fa.fa-heart
          %br/
          %p.muted © 2014 Berlin
          %a
            = link_to 'Imprint', imprint_path
          %br
          %a
            = link_to 'Team', team_path
          %br
          %a
            = link_to 'About us', about_us_path
          %br
          %a
            = link_to 'How does it work?', faq_path


%section#copyright
  .container
    .row
      .col-md-6.col-sm-6.copy-left
        %p
          Copyright © 2014
          = succeed "." do
            %strong Elskamor
      .col-md-6.col-sm-6.copy-right
        %ul.list-inline.social-icon
          %li
            %a.icon-twitter{"data-original-title" => "Twitter", "data-placement" => "top", href: "https://twitter.com/Elskamor", rel: "tooltip", title: "", target: "_blank"}
              %i.fa.fa-twitter
          %li
            %a.icon-facebook{"data-original-title" => "Facebook", "data-placement" => "top", href: "https://www.facebook.com/elskamor", rel: "tooltip", title: "", target: "_blank"}
              %i.fa.fa-facebook-square
          %li
            %a.icon-youtube{"data-original-title" => "Youtube", "data-placement" => "top", href: "https://www.youtube.com/user/Elskamor", rel: "tooltip", title: "", target: "_blank"}
              %i.fa.fa-youtube
          %li
            %a.icon-instagram{"data-original-title" => "Instagram", "data-placement" => "top", href: "http://instagram.com/elskamor", rel: "tooltip", title: "", target: "_blank"}
              %i.fa.fa-instagram
          %li
            %a.icon-pinterest{"data-original-title" => "Pinterest", "data-placement" => "top", href: "http://www.pinterest.com/Elskamor/", rel: "tooltip", title: "", target: "_blank"}
              %i.fa.fa-pinterest

app/views/layouts/_head.html.haml
%head
  / TradeDoubler site verification 2478718
  %meta{charset: "utf-8"}/
  %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
  %meta{content: "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
  %meta{content: "letsleaveitempty", name: "author"}/
  %link{href: "assets/favicon.ico", rel: "shortcut icon"}/
  %title Elskamor
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  = render partial: 'layouts/head'

  = render partial: 'layouts/body'

  %section#content
    .container
      = yield

  = render partial: 'layouts/footer'

app/views/offer_inquiries/_form.html.haml
= simple_form_for :inquiry do |f|
  = f.input :name
  = f.input :phone, required: false
  = f.input :email, as: :email
  = f.input :message, as: :text, hint: "* required fields"
  = f.button :submit, 'Send'

app/views/offer_inquiries/index.html.haml
%table.table.table-striped
  %tr
    %th id
    %th offer
    %th name
    %th phone
    %th email
    %th message
  - @inquiries.each do |inquiry|
    %tr
      %td= inquiry.id
      %td= inquiry.offer.name
      %td= inquiry.name
      %td= inquiry.phone
      %td= inquiry.email
      %td= inquiry.message

app/views/offer_inquiries/show.html.haml
= @inquiry.to_s

app/views/offers/_form.html.haml
= form_for(@offer) do |f|
  - if @offer.errors.any?
    #error_explanation
      %h2
        = pluralize(@offer.errors.count, "error")
        prohibited this post from being saved:
      %ul
        - @offer.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name, {style: "width: 800px; height: 50px;"}
  .field
    = f.label :title
    %br/
    = f.text_field :title, {style: "width: 800px; height: 50px;"}
  .field
    = f.label :dates
    %br/
    = f.text_field :dates, {style: "width: 800px; height: 50px;"}
  .field
    = f.label :main_image_link
    %br/
    = f.text_field :main_image, {style: "width: 800px; height: 50px;"}
  .field
    = f.label :country
    %br/
    = f.text_field :country, {style: "width: 800px; height: 50px;"}
  .field
    = f.label :city
    %br/
    = f.text_field :city, {style: "width: 800px; height: 50px;"}
  .field
    = f.label "Zip code - only digits eg \"12345\""
    %br/
    = f.text_field :zip_code, {style: "width: 800px; height: 50px;"}
  .field
    = f.label :address
    %br/
    = f.text_field :address, {style: "width: 800px; height: 50px;"}
  .field
    = f.label :short_teaser
    %br/
    = f.text_area :short_teaser, {style: "width: 800px; height: 200px;"}
  .field
    = f.label :description
    %br/
    = f.text_area :description, {style: "width: 800px; height: 600px;"}
  %br
  %hr
  .field
    = f.label :published
    %br/
    = f.check_box :published
  %br
  .actions
    = f.submit

app/views/offers/edit.html.erb
<h1>Editing offer</h1>

<%= render 'form' %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>

app/views/offers/index.html.haml
%section#content
  .container
    .row
      - if user_signed_in?
        .text-center
          = link_to ' Add New Offer', new_offer_path, class: 'btn btn-lg btn-primary'
        %br
        %br
        %br

    .row
      - @offers.each do |offer|
        - if offer.published || user_signed_in?
          .post-container.col-md-6.col-xs-12
            .post-content.no-padding
              = image_tag(offer.main_image, style: "height: 350px")
            .post-content
              .heading-title.heading-small
                %h2
                  = link_to offer.title, offer_path(offer)
                  %br
                  %small= ["#{offer.city}", "#{offer.country}"].join(', ')
              %p{style: "height: 200px"}
                = strip_tags(offer.short_teaser)
              .post-link
                %a{:href => offer_path(offer.id)}
                  %span See More Details
                  - if user_signed_in?
                    %br
                    %br
                    .well.well-small.text-center
                      = link_to 'Edit', edit_offer_path(offer)
                      = link_to 'Delete', offer, method: :delete, data: { confirm: 'Are you sure you want to delete this offer?' }

app/views/offers/new.html.erb
<h1>New offer</h1>

<%= render 'form' %>

<%= link_to 'Back', offers_path %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.haml
%section#content
  .container
    .row
      - if user_signed_in?
        .text-center
          = link_to 'Add New Post Here', new_post_path, class: 'btn btn-lg btn-primary'
        %br
        %br
        %br

    .row
      - @posts.each do |post|
        - if post.published || user_signed_in?
          .col-md-6
            .post-content
              = image_tag(post.main_image, style: "height: 300px")
              .heading-title.heading-small
                %h2
                  = link_to post.title, post_path(post)
              .post-meta
                %span
                  = post.created_at.strftime("on %A, %B %e, %Y")
              %p{style: "height: 170px"}
                = truncate(strip_tags(post.body), length: 250)
              .post-link
                %a{:href => post_path(post)}
                  %span Read More
                  - if user_signed_in?
                    %br
                    %br
                    %hr
                    %br
                    .well.well-small
                      = link_to 'Edit', edit_post_path(post)
                      = link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure you want to delete this post?' }

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/shared/_quote_box.html.haml
.post-container
  .post-content
    %blockquote
      %p Dikehidupan manusia itu memang banyak usaha yang tidak membuahkan hasil. Usaha mendapatkan cintamu misalnya..
      %small Bardiman
  .post-atribut
    .row
      .col-md-4.col-sm-4.col-xs-4
        %a{href: "#"}
          %span
            %i.fa.fa-heart
            2000
      .col-md-4.col-sm-4.col-xs-4
        %a{href: "#"}
          %span
            %i.fa.fa-comments
            400
      .col-md-4.col-sm-4.col-xs-4
        %a{href: "#"}
          %span
            %i.fa.fa-eye
            2500